/*
Write a selenium script to double click and right click the elements on 
http://demo.guru99.com/test/simple_context_menu.html
*/

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;

public class Question_4 {

    public static void main(String[] args) throws InterruptedException {
        

        // Set path to GeckoDriver
        System.setProperty("webdriver.gecko.driver", "E:\\Sem_3\\STQA\\Selenium_setup\\geckodriver.exe");
        WebDriver driver = new FirefoxDriver();

        // Open the Guru99 Context Menu demo page
        driver.get("http://demo.guru99.com/test/simple_context_menu.html");
        driver.manage().window().maximize();

        // Create Actions object
        Actions action = new Actions(driver);

        WebElement rightClickBtn = driver.findElement(By.cssSelector("span.context-menu-one.btn.btn-neutral"));

        // Perform right-click (context click)
        action.contextClick(rightClickBtn).perform();
        System.out.println("Performed right click on the 'Right Click Me' button.");

        Thread.sleep(1000);

        WebElement editOption = driver.findElement(By.xpath("//ul/li/span[text()='Edit']"));
        editOption.click();
        System.out.println("Clicked on 'Edit' option from context menu.");

        // Handle the alert that appears after clicking "Edit"
        driver.switchTo().alert().accept();
        System.out.println("Alert accepted after clicking 'Edit'.");

        Thread.sleep(1000);

        WebElement doubleClickBtn = driver.findElement(By.cssSelector("button[ondblclick='myFunction()']"));

        // Perform double-click
        action.doubleClick(doubleClickBtn).perform();
        System.out.println("Performed double click on the button.");
        Thread.sleep(2000);
        // Handle alert generated by double-click
        driver.switchTo().alert().accept();
        System.out.println("Alert accepted successfully after double click!");

        Thread.sleep(2000);
        driver.quit();
    }
}

